### ISSUE TITLE
[Request] Add spanish translation

### ISSUE THREAD

**Issue by roliverosc** [osmc/skin.osmc#172]
Hello osmc staff I would like the Spanish language to be available for the skin. I have all the strings translated except for the new added.
I tried to do it through transifex but the transifex file is quite out of date. If you want I can launch an extraction request when I update it.

**Comment by Ch1llb0** [comment]
We've heard your request - I believe, you've opened a PR with this before already. Unfortunately, the situation hasn't changed as of now. I'll make sure to contact you here in case we switch from the Transifex approach and decide to do the translation on our side. We'd be happy to ask you for a Spanish language version, if we should decide to change course. 👍

**Comment by roliverosc** [comment]
Ok, thank you @Ch1llb0 .

**Comment by Ch1llb0** [comment]
We've now decided to go with our own translation system (WebLate) that we're in the process of setting up. We'll be actively looking for contributors who're willing to help translate our skin and later also other parts of OSMC to other languages than English. Would you be interested in helping us with a Spanish translation of our skin and possibly other language strings?

**Comment by samnazarko** [comment]
There's more information about how to get involved here: https://discourse.osmc.tv/t/help-needed-translating-osmc-in-to-other-languages/89558.
