### ISSUE TITLE
Change channel group in OSD

### ISSUE THREAD

**Issue by plonster76** [osmc/skin.osmc#212]
hi, 
i added the possibility to change the channel group in DialogPVRChannelsOSD.xml onleft/onright.
maybe you can implement this as an option. not everyone has just on channel group. 

[DialogPVRChannelsOSD.xml](https://gist.github.com/plonster76/e12989030006c59890a75636114964cf)

**Comment by Ch1llb0** [comment]
Will look into this for the next update 👍

**Comment by Ch1llb0** [comment]
I've added this feature with the newest commit: https://github.com/osmc/skin.osmc/commit/6f31bc1477c218f118a4385465e33aea67ea0dca

![screenshot000](https://user-images.githubusercontent.com/36623079/84571840-57535480-ad96-11ea-9f40-32018166d634.png)

You'll see this change in the next OSMC update. 👍

**Comment by plonster76** [comment]
great!!! many thanks for the quick implementation.
