### ISSUE TITLE
Adjustment Coordinates_DialogPVRChannelsOSD.xml

### ISSUE THREAD

**Issue by plonster76** [osmc/skin.osmc#217]
Hi Ch1llb0,
i adjusted the position of the ChannelNumberLabel in Coordinates_DialogPVRChannelsOSD.xml.

the label has now the same distance to the window border on the right side like the description label on the left side.

[Coordinates_DialogPVRChannelsOSD.xml](https://gist.github.com/plonster76/516eedc37b53576f52d30424a3b9c3a3) 

maybe you can include the change in the official version.

thanks

**Comment by Ch1llb0** [comment]
Sry, didn't notice this issue before... The PVR OSD dialogs are now completely reworked as the alignment was completely off which I hadn't noticed before. This is what they will look like with the next update:

![screenshot000](https://user-images.githubusercontent.com/36623079/87855000-d5ff5c80-c915-11ea-9bc9-d55648cda7a1.png)
![screenshot001](https://user-images.githubusercontent.com/36623079/87855001-d7308980-c915-11ea-92d3-ab80675a45de.png)

Thank you for pointing me to this! 👍

**Comment by plonster76** [comment]
hi are these changes already on github?
can't just wait to try out :-)

**Comment by Ch1llb0** [comment]
Not yet, no.

**Comment by Ch1llb0** [comment]
The changes have been added now: https://github.com/osmc/skin.osmc/commit/2d028cd84caba506c88d2fdedcf7f6652eace62e
