### ISSUE TITLE
Broken on Matrix Release AndroId TV

### ISSUE THREAD

**Issue by seniorm0ment** [osmc/skin.osmc#303]
AndroidTV Kodi updated to Matrix 19.

The OSMC skin no longer shows up under skins, it reverted, and when I try to install the zip it errors stating dependency on xmbcgui v 5 14 0 could not be satisfied.

I ensured to grab the latest release.

**Comment by samnazarko** [comment]
Are you sure you downloaded the Matrix version?

On 26 Feb 2021, at 02:34, john <notifications@github.com> wrote:

﻿

AndroidTV Kodi updated to Matrix 19.

The OSMC skin no longer shows up under skins, it reverted, and when I try to install the zip it errors stating dependency on xmbcgui v 5 14 0 could not be satisfied.

I ensured to grab the latest release.

**Comment by seniorm0ment** [comment]
I probably didn't, do you have a link to it?
The latest OSMC skin release I see here is 18.5.0 from Dec 2 which is what I grabbed.

**Comment by samnazarko** [comment]
The latest Matrix version is already in this repository.
It's version is 18.9.9.

You've downloaded the Leia (v18) version, which is why it doesn't work on v19.

**Comment by seniorm0ment** [comment]
That makes sense, however I do not see v18.9.9
https://github.com/osmc/skin.osmc
The latest there is 18.5.0.

I do see the github branch is labeled matrix, but again I see nothing newer under releases.
I tried clicking Code > Download Zip to download the matrix branch, then rename as osmc.skin.zip, however it doesn't import into kodi due to "invalid file structure".

**Comment by seniorm0ment** [comment]
Still have not figured this out

**Comment by samnazarko** [comment]
The Matrix branch is indeed current, and working here.

**Comment by aravindh-murugesan** [comment]
I just downloaded the entire code from matrix branch and installed as zip. Worked perfectly fine.

**Comment by seniorm0ment** [comment]
Got it working, don't know what I did differently tbh but it imported this time.
Thanks, sorry for the bother

**Comment by aravindh-murugesan** [comment]
Glad you got it working. Please close the issue. @grravity
