### ISSUE TITLE
OSMC theme and Kodi 19

### ISSUE THREAD

**Issue by dartoi** [osmc/skin.osmc#305]
OSMC theme is not working with Kodi v19.0

**Comment by Ch1llb0** [comment]
Can you elaborate what you mean, please? The OSMC Skin has been adapted for v19 already and should work.

**Comment by dartoi** [comment]
Error: "The dependency on xbmc.gui version 5.14.0 may not be satisfied."  I tried to install the osmc master skin archive and also the scope archive, but the same error appears.

**Comment by Ch1llb0** [comment]
I believe you have an old v19 version installed. The OSMC Skin is made for xbmc.gui version [5.15.0](https://github.com/osmc/skin.osmc/blob/matrix/addon.xml) which is a requirement [since last April](https://forum.kodi.tv/showthread.php?tid=343076&pid=2941389#pid2941389).

Are you downloading the archive straight from our Matrix branch or the latest release (which is for v18 as those releases are bound to OSMC release - which are still based on v18)?

**Comment by dartoi** [comment]
I have installed into Amazon Fire TV Stick (Android 5.1.1) the .apk [Kodi v19.0 "Matrix" ARMV7A (32BIT)](https://mirrors.kodi.tv/releases/android/arm/kodi-19.0-Matrix-armeabi-v7a.apk?https=1) from Official website, but appear the same error: "**The dependency on xbmc.gui version 5.14.0 may not be satisfied.**"

On Amazon Fire Stick I had Kodi v18 installed, so I uninstalled the old version and installed v19.

**Comment by Ch1llb0** [comment]
Have you installed the newest v19 version of the OSMC Skin from the Matrix branch?

**Comment by dartoi** [comment]
I have download the .apk file in my Android smartphone from this link: https://mirrors.kodi.tv/releases/android/arm/kodi-19.0-Matrix-armeabi-v7a.apk?https=1

and then I have installed .apk from AppToFire.

**Comment by Ch1llb0** [comment]
I'm asking about the skin, not Kodi ;) Which version of the OSMC Skin have you tried installing? A "release" version or a .zip from the Matrix branch?

**Comment by dartoi** [comment]
I tried to install the following OSMC Skin from zip file:

1. OSMC Skin (Scope edition) v18.5.0
2. OSMC Skin v18.5.0
3. skin.osmc-master (v18.2.0)

When I try to install from Kodi (.zip 1,2,3) I get the same error.

**Comment by Ch1llb0** [comment]
As I said before, you have to download the zip from the Matrix branch for the skin to work under v19. The release versions are still v18 compatible only (everything below v18.9.9).

> Are you downloading the archive straight from our Matrix branch or the latest release (which is for v18 as those releases are bound to OSMC release - which are still based on v18)?

This should work: https://github.com/osmc/skin.osmc/archive/matrix.zip

**Comment by dartoi** [comment]
Thanks a lot for this: https://github.com/osmc/skin.osmc/archive/matrix.zip
It's working properly.

**Comment by Ch1llb0** [comment]
Glad to hear you're set and good to go!
