### ISSUE TITLE
[Bug] OSMC keeps crashing when loading widgets

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#324]
Hi, im so sorry for making this a bug but OSMC keeps crashing for some odd reason. I have all the addons i need and Language Invoker is disabled for all addons but for some reason, i still keep crashing when starting kodi. There are times when it doesn't crash when loading widgets and there are most times that it has been crashing for some odd reason. Here is some of the logs that show which process crashed. 
 
[kodi.log](https://github.com/osmc/skin.osmc/files/6307255/kodi.log)

[kodi_stacktrace-19.0 Git_20210218-f44fdfbf67-20210413-192256.txt](https://github.com/osmc/skin.osmc/files/6307256/kodi_stacktrace-19.0.Git_20210218-f44fdfbf67-20210413-192256.txt)

**Comment by samnazarko** [comment]
>2021-04-13 19:22:52.115 T:12796    INFO <general>: Starting Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: Windows NT x86 64-bit

You are not using OSMC.
Please start a bug report on the Kodi forums.
