### ISSUE TITLE
[Skin Bug] OSMC skin keeps crashing when loading widgets

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#325]
Sorry i was not specific enough on Issue #324 

OSMC Skin keeps crashing and i have no idea why. 

Language Invoker is disabled for all addons but for some reason, i still keep crashing when starting kodi. There are times when it doesn't crash when loading widgets and there are most times that it has been crashing for some odd reason.

**Comment by Goldenfreddy0703** [comment]
@samnazarko its a skin bug, not a osmc bug, atleast give a reason then closing this issue

**Comment by samnazarko** [comment]
You should provide proper logs, then we can explore.
GitHub is for confirmed issues only.
