### ISSUE TITLE
[Bug] Your skin keeps crashing, i have a video so atleast look at this

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#326]
https://drive.google.com/open?id=1Eow8iB0uICo1OFPXq35wI4ektbcMGNiR

Dude, your skin keeps crashing Its not osmc, its your skin. 

Atleast look at the video instead of closing it without a reason.....like seriously

**Comment by samnazarko** [comment]
Please provide debug logs and not a video URL which people have to request access to. 

Please also provide instructions on how to reproduce a crash.

**Comment by Goldenfreddy0703** [comment]
Sorry but i will be gladly too, give me a few min. Thank you for listening this time

**Comment by Goldenfreddy0703** [comment]
[kodi.log](https://github.com/osmc/skin.osmc/files/6307583/kodi.log)
[kodi.old.log](https://github.com/osmc/skin.osmc/files/6307584/kodi.old.log)
[kodi_stacktrace-19.0 Git_20210218-f44fdfbf67-20210413-192256.txt](https://github.com/osmc/skin.osmc/files/6307585/kodi_stacktrace-19.0.Git_20210218-f44fdfbf67-20210413-192256.txt)
[kodi_stacktrace-19.0 Git_20210218-f44fdfbf67-20210413-211848.txt](https://github.com/osmc/skin.osmc/files/6307586/kodi_stacktrace-19.0.Git_20210218-f44fdfbf67-20210413-211848.txt)
[kodi_stacktrace-19.0 Git_20210218-f44fdfbf67-20210413-211900.txt](https://github.com/osmc/skin.osmc/files/6307587/kodi_stacktrace-19.0.Git_20210218-f44fdfbf67-20210413-211900.txt)
[kodi_stacktrace-19.0 Git_20210218-f44fdfbf67-20210413-211913.txt](https://github.com/osmc/skin.osmc/files/6307588/kodi_stacktrace-19.0.Git_20210218-f44fdfbf67-20210413-211913.txt)

I have a lot of crash bugs and i feel like it could be due to your skin 

im going to close this issue for now cause im going to start over but once im done, i will open this issue up again and show how to reproduce it, thank you for listening.

**Comment by samnazarko** [comment]
>I have a lot of crash bugs and i feel like it could be due to your skin

I suggest changing to Estuary -- officially supported skin and seeing if the issues persist. If they do, you should try and resolve them before coming back to us.

**Comment by Goldenfreddy0703** [comment]
Ok so i figured out how to reproduce this bug. 
1. Download Seren from Nixgates Repository
https://nixgates.github.io/packages
![1](https://user-images.githubusercontent.com/62456796/114662507-cf481f00-9cc6-11eb-9d51-6de326e11ea7.PNG)
2. Go to the addon configuration settings into seren and go to shortcuts and click Toggle Re-Use Language Invoker that disables it.
![2](https://user-images.githubusercontent.com/62456796/114662532-d7a05a00-9cc6-11eb-93ff-de99a061b256.PNG)
3. Now go to Configure skin and go Customize main menu and go to videos tab
![3](https://user-images.githubusercontent.com/62456796/114662551-dd963b00-9cc6-11eb-8f63-b9fbd1cd8fcd.PNG)
4. Now that your in the default Videos tab, go to Manage Widgets
![4](https://user-images.githubusercontent.com/62456796/114662561-e424b280-9cc6-11eb-8653-facf089d1669.PNG)
5. Now that your in Manage Widgets, Click Select Widget 
![5](https://user-images.githubusercontent.com/62456796/114662575-ea1a9380-9cc6-11eb-9305-aad8a0c8a4be.PNG)
6. Go to Addons > Video add-ons > Seren > Discover Movies > Most 
Popular
![6](https://user-images.githubusercontent.com/62456796/114662605-fa327300-9cc6-11eb-9735-6c0f7b306702.PNG)
7. Click Use as widget and the hit done. 
![7](https://user-images.githubusercontent.com/62456796/114662619-028aae00-9cc7-11eb-819a-eeab42fc105d.PNG)
8. Hit Backspace a few times and wait for 5 sec
![8](https://user-images.githubusercontent.com/62456796/114662633-0b7b7f80-9cc7-11eb-9b8c-3c74e5a1237c.PNG)
9. Restart your kodi 5 times until you see a crash in one of them. 
![9](https://user-images.githubusercontent.com/62456796/114662660-159d7e00-9cc7-11eb-9ec1-18293b25da76.PNG)

I hope this shows you the error im talking about and i hope you see what im talking about.

**Comment by Goldenfreddy0703** [comment]
Im 100% sure that it could be your skin thats causing the bug cause most skins i have tried have never had a bug like this. 

Btw sorry about the video link being restricted, it should be unrestricted
https://drive.google.com/open?id=1Eow8iB0uICo1OFPXq35wI4ektbcMGNiR

**Comment by Ch1llb0** [comment]
What you're doing there is 100% relying on the skinshortcuts script which provides the customization dialog as well as the widget itself. It sounds to me like the script is doing something wrong here or is provided with something that Kodi can't handle.

In any case, this is not something the OSMC Skin can do anything about. What I would suggest is testing this with a skin that also uses the skinshortcuts script, like e.g. Aeon Nox: SiLVO and report to the skinshortcuts script thread over at the Kodi forum: https://forum.kodi.tv/showthread.php?tid=178294

**Comment by Goldenfreddy0703** [comment]
In a way i have tried multiple skins using the skinshortcuts script. I have tested Auramod, Titan, Artic Horizon, and other skins back then. I can try Aeon Nox: SiLVO but i dislike the skin cause its based off of confluence skin.

**Comment by graham8** [comment]
Nobody's asking you to change to another skin. Please if you could **test** it so we know if it's an issue with skinshortcuts or not.

"back then" sounds like you might have been on a different Kodi version.

**Comment by Goldenfreddy0703** [comment]
oh yeah @graham8 that is what im going to do, i just need to download it 
the repo is taking forever tho

**Comment by Goldenfreddy0703** [comment]
Ok so 1 out of 10 times, it does crash so it could be due to skinshortcuts  script. Im sorry i thought it would be your skin for this bug. That was my fault and i should have tried more skins and test them before making this a bug. I thought it would be due to delay or something.

**Comment by Ch1llb0** [comment]
Please post logs and a description of the issue over in the Kodi thread I linked to. It will benefit everyone, if this is fixed 👍🏻

**Comment by Goldenfreddy0703** [comment]
Thank you and i will try
