### ISSUE TITLE
[bug] Skin Helper Service Widgets Saying Widgets Disabled even though i can configure it. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#341]
Hey, sorry for bothering you but i noticed a bug in your skin or its just like that for other reasons. I installed Marcelveldt Repository and i installed all the Recommended addons or scripts but one of the scripts: Skin Helper Service Widgets is saying that its disabled. I enabled that script and i can configure it successfully. The only bug i encountered was that it just said disabled in the skin settings even tho i can configure it. 

Here is the Marcelveldt Repository to reproduce the steps on a fresh kodi install: https://github.com/kodi-community-addons/repository.marcelveldt

Here is a screenshot of the bug i encountered. 
![Disabled Bug](https://user-images.githubusercontent.com/62456796/121654678-fa06e780-ca6b-11eb-9035-4aa64d496818.PNG)

To reproduce the steps:
1. Start a fresh installation of kodi and start kodi up.
2. Close kodi and go to its app data files and put skin.osmc into the addons folder. 
3. Start kodi again and then go to file manager.
4. Add https://kodi-community-addons.github.io/repository.marcelveldt/ as a Kodi file source (file manager) and give it a name such as "marcelveldt repo"
5. Then you can install the repo zip from that file source. Install from zip > choose the file source you just made > select the repo zip to install
6. enable the repo that you installed. (if repo already enabled then skip this step)
7. Switch to the osmc skin and go to configure skin
8. Once your in the skin setting menu, go to addons and install all the recommended Skin addons. 
9. After installing all the recommended Skin addons, try enabling the Skin Helper Service Widgets and if it says disabled then click it again and should takes you to the configuration settings even tho it says disabled.
10. The bug is that it says disabled even tho you can configure it.

PS: If you would like me to make a video for this bug and how i did it. Please tell me and i will get right back to you and make one. Sorry i did not make one sense its 4:30 am for me at this time.

**Comment by Ch1llb0** [comment]
Are you on one of our v19 test builds or the latest stable OSMC update - or to put it differently: Have you encountered this bug with the v18 OSMC skin or the v19 version?

**Comment by Goldenfreddy0703** [comment]
I have encountered  this bug on V19 version of OSMC skin and updating it to the latest test builds. (Sorry for the late reply)

**Comment by Goldenfreddy0703** [comment]
Im not on the os version of osmc, im just using the lastest test skin that was updated 2 days ago on when you Added translation using Weblate (Czech (cs_cz)).

**Comment by Ch1llb0** [comment]
Will check, thx for the hint!

**Comment by Ch1llb0** [comment]
Found the issue... Fixes with this commit: https://github.com/osmc/skin.osmc/commit/c0ea60c85233b52cfa93f29ae868d6cac766495a Will be showing up in staging soon!

**Comment by Goldenfreddy0703** [comment]
Hey thank you very much and you are the best and again, love your skin very much.
