### ISSUE TITLE
[Feature Request] Having a horizontal menu for osmc?

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#355]
Hi, I know this request might mostly get rejected and i can understand if you and your team disagrees with it but have you guys ever considered adding a horizontal main menu and making it look like the the old classic Confluence Skin with a beautiful skin design like how you guys made the vertical main menu on osmc? I just think adding a horizontal menu would be really cool for osmc and i would really like this to be a request just because of how beautiful this skin is. 
![image](https://user-images.githubusercontent.com/62456796/131545685-7db76456-abc8-4da8-8d85-ee264d15e66e.png)
This is an example of what you guys did when configuring an addon. It could be the same when making a horizontal main menu in the future if its possible. 

If this would be possible, that would be great and i would love to try it out someday if this Feature Request does not get rejected. 
Thank you for hearing me out.

**Comment by Ch1llb0** [comment]
Hey there... This is on the list of things to be considered and looked at. As it's quite a big change that's needed and as the skin has been designed to mainly be a vertical 'list' style one, we haven't decided whether this will be added or not.

**Comment by Goldenfreddy0703** [comment]
ahh i understand, thank you very much for responding and im very happy to hear that its on your considered list. I really love this skin especially how beautiful the menu and texture designs are. 

Again, thank you very much

**Comment by Goldenfreddy0703** [comment]
Hey so i might as well close this cause you said "not a confirmed issue or bug." Idk why you have not closed this cause this was a feature request and feature request can only be on the osmc community forum, this might not be considered in the future just cause of the new design and that you deprecated the old design so might as well close it. 

This may open in a few years but who knows and there's not really a point at the moment to have this request. Should have closed this request earlier sense its a feature request. 

Anyway thanks for putting this on your list and goodbye.
