### ISSUE TITLE
How to change the background color of the HOME, Videos...  like v18 ?

### ISSUE THREAD

**Issue by keii3** [osmc/skin.osmc#372]
Hello everyone.  

Since v19, the background of the left pane of the Home screen has been colored.  
Where is the setting to make this the same as v18, transparent?  

To be honest, I don't need the colored background and it's unpleasant.  
Every time I go back and forth between the menus, my eyes flicker and I feel sick.  

This one.  
![v19_home](https://user-images.githubusercontent.com/48112883/138216816-3bf4eb68-696e-4d6a-afff-d64a5d920fcd.jpg)  
and this.  
This difference in width exacerbates the symptoms.  
![v19_videos](https://user-images.githubusercontent.com/48112883/138216817-a414f22e-e5ab-4ebe-ac47-79ca208397d0.jpg)  

I need simple like this (v18)...
![v18_home](https://user-images.githubusercontent.com/48112883/138216804-9e1d3c28-e380-48b9-9ef7-8ca4011c09d4.jpg)  
![v18_videos](https://user-images.githubusercontent.com/48112883/138216811-114b8517-c35e-4b8e-a7b1-5f673d967e1b.jpg)  

Please tell me how to make it the same as v18.

**Comment by keii3** [comment]
In "OSMC Skin v19.0.0" in the release, it was temporarily avoided by making the following corrections.

xml/Coordinates_Includes_Windows_Dialogs.xml

row 97, 160

```xml
    <param name="texture1">common/overlayleft.png</param>
                                    ↓
    <param name="texture1">common/overlay.png</param>
````

**Comment by Ch1llb0** [comment]
You may change this by setting the background colour to a high opacity via the custom colour settings our skin offers. This way you can make the background overlay less visible. Our new design is an integral part of the skin now though: The left and right side (or bottom and top in horizontal views) cannot be configured independently as they always use the same colour with different shading and opacity.

This section is only for confirmed bugs though. Please post this kind of question on our forum.
