### ISSUE TITLE
[Feature Request] Adding the old overlays and bringing back the Overlay Colour option.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#377]
-Hey there, sorry to bother but i just updated your skin and its been a while and i was wondering if you guys could have an option to bring back some of the old overlays, I really liked the old overlays because they reminded me of the kodi confluence skin with a translucent theme and seeing the new skin having a different type translucent theme does not look as good.
**New Translucent themes**
![image](https://user-images.githubusercontent.com/62456796/139502265-e7e0056e-4dda-4804-94a1-48af6276bd7c.png)
![image](https://user-images.githubusercontent.com/62456796/139502368-b4195c7c-bdb2-45cd-aaf4-6e591f4e2972.png)
**Old Translucent themes**
![image](https://user-images.githubusercontent.com/62456796/139500567-007310b3-3ddc-46f5-bb4e-929b785647bb.png)
![image](https://user-images.githubusercontent.com/62456796/139500710-042437b8-647d-4690-aa53-07e6bb03aa03.png)

-One other request is bringing back the old Overlay Colour option cause without it, i can no longer edit just the side menu, i would have to edit the background colour which is annoying. 
**Old Custom Options with the Overlay Colour Option**
![image](https://user-images.githubusercontent.com/62456796/139502049-d1d49b5d-ae68-4ec4-9a45-7fe61f75192a.png)
**New Custom Options without the Overlay Colour Option**
![image](https://user-images.githubusercontent.com/62456796/139502196-31ea8deb-6deb-495d-8720-f0620c76e55f.png)

Again, Thank you very much for hearing me out and i hope this will be considered in order to use your updated skin more.

**Comment by Ch1llb0** [comment]
Please use this section for confirmed issues only and post in the feature request section of our forum.

**Comment by Goldenfreddy0703** [comment]
But don't you guys barely read the forums?
