### ISSUE TITLE
[Bug] Misssing Overlay Colour option in which it is a confirmed issue.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#378]
Hey there, sense you said that this section is for confirmed issues only, I can't seem to find the Overlay Colour option and was wondering why you guys took that a way or maybe it was a bug that caused it to go away without an explanation so if this is an issue, I would like to know why or the reasoning for that. 

**Old Custom Options with the Overlay Colour Option**
![image](https://user-images.githubusercontent.com/62456796/139592784-c21c2bc4-423e-4887-99d3-d1b90216b0bf.png)
**New Custom Options without the Overlay Colour Option**
![image](https://user-images.githubusercontent.com/62456796/139592787-c95b24ef-d062-436e-a3f7-c0042b25d981.png)

Thank you and one last thing is you may want to remove #355 sense it was a feature request and not an issue.

**Comment by Ch1llb0** [comment]
Double posting won't help - this is not a confirmed issue or bug, but a design choice. Double posting here on triple posting on the forum won't help... If there's demand to adjust our design in certain aspects, we will consider it through our feature request forum section.

**Comment by Goldenfreddy0703** [comment]
> 
> 
> Double posting won't help - this is not a confirmed issue or bug, but a design choice. Double posting here on triple posting on the forum won't help... If there's demand to adjust our design in certain aspects, we will consider it through our feature request forum section.

oh so its not a bug then, it was just a design choice. Welp im going to just use a previous version of your skin for now on and make a pull request and merge some of your commits in the future for the time being.
