### ISSUE TITLE
[Bug] Your enabled button is grey and not white. Fix issue of ignore your mistake or bug.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [osmc/skin.osmc#382]
Ok lets get strait to the point sense i don't like your skin anymore. Whenever you add a new widget, the enabled button is greyed out and not white.  
**Greyed out and not white**
![image](https://user-images.githubusercontent.com/62456796/141022103-c2bd4eb0-fb18-4b9c-9266-ecd8d4b1ca31.png)
**Expected result**
![image](https://user-images.githubusercontent.com/62456796/141022234-4b69114d-bc73-47e5-9562-3f8e790e88f9.png)

You cannot deny that this is not a bug and if you close this issue then your ignoring your own mistakes so yeah. Anyway, your team should have noticed this bug on your new skin and you should too. 

Have a nice day and you guys are strict. Goodbye

**Comment by samnazarko** [comment]
Thanks for providing your feedback on the forums, the OSMC support portal and GitHub here.

If this is indeed a bug, I am sure that this will be confirmed in due course.

**Comment by Goldenfreddy0703** [comment]
Sure....but this isn't a forum, it's an issue page to submit bugs just like @Ch1llb0 said. If i was giving feedback then i would be on your osmc feedback forums but i was suspended for duplicate post for posting on github and the osmc forums. I did not know github was in your terms of service and i think you guys should update that.

Please understand that this is not feedback and nor a feature request. Its a bug and you should know that and confirm with your team if you have to.

**Comment by samnazarko** [comment]
You were suspended for spamming the forum, necromancing old posts and making several posts about the same topic.

If this is a bug, it will be fixed.

**Comment by Goldenfreddy0703** [comment]
Ok so messaging a mod or a dev is spamming apparently and making three post about a futures request, a bug, and asking peoples opinions in discussion is spamming and i don't even know what necromancing is so you might as well show me the definition of that.

**Comment by samnazarko** [comment]
We are interested in solving technical issues here.
If there is an issue, this will be solved.

Thanks for your understanding.

**Comment by Ch1llb0** [comment]
Changed the localize used for the setting. It was working as expected on both Windows and OSMC here. Not sure what the issue should've been on the user's setup.
