### ISSUE TITLE
4:3 skin for Kodi 18.7 using the archived branch

### ISSUE THREAD

**Issue by moonbit5** [osmc/skin.osmc#387]
I'm attempting to use skin.osmc with Kodi version 18.7 on a CRT display using a Raspberry Pi 4B. 

Kodi is up and running but I've not been able to install the 4:3 version of the skin after following these really clear instructions: https://discourse.osmc.tv/t/osmc-skin-4-3-aspect-ratio-support/86436/2

After editing the addon.xml the zip fails to install. I've looked through the logs and there's nothing mentioning why it's failing. The error that pops up in the notification says it failed do to 'invalid structure'.

I'm using the archived leia branch of the skin and following the intructions exactly. Any idea what could be causing the error?

**Comment by Ch1llb0** [comment]
Does this work? [skin.osmc.43.zip](https://github.com/osmc/skin.osmc/files/7602673/skin.osmc.43.zip)
