### ISSUE TITLE
Plugin settings window

### ISSUE THREAD

**Issue by nixxo** [osmc/skin.osmc#396]
From kodi19 they recommend to convert plugin settings to the format Kodi uses internally: https://kodi.wiki/view/Add-on_settings_conversion

So, the plugin setting window should look like the Kodi settings windows and display "Settings level toggle" and the Help string.

This is how the default skin looks like
![screenshot00001](https://user-images.githubusercontent.com/426049/144709167-9003f230-f657-4c5e-a184-1e7649d59d24.png)

This is OSMC skin
![screenshot00002](https://user-images.githubusercontent.com/426049/144709171-85bad599-ed34-4171-90d3-2ca259addc73.png)

Also if is possible to add the "title" of the plugin in the top left corner like in the Kodi setting windows it would be nice:
![screenshot00000](https://user-images.githubusercontent.com/426049/144709279-8ab07cab-3eb7-4f82-8c3e-36f21f6d8c1c.png)

**Comment by Ch1llb0** [comment]
Everything should be addressed with this commit: https://github.com/osmc/skin.osmc/commit/f2a9bad1f086134230a5fb7ab84ab0458b09d4f3

![screenshot00000](https://user-images.githubusercontent.com/36623079/144717554-9bcc70da-e350-4544-b4a2-e3e27194c786.png)

Thank you for the report! 👍🏻

**Comment by nixxo** [comment]
Nice.
