### ISSUE TITLE
[bug] Missing buttons on the OSD when playing a Playlist from a widget

### ISSUE THREAD

**Issue by nixxo** [osmc/skin.osmc#402]
I have a widget in the home screen from an addon that when run generates a playlist of video to play. When I run the widget element directly (by clicking the OK button) the video starts but some buttons in the OSD related to the playlist are missing.
When I run the same widget element from the context menu (Context menu button, Play) the buttons are displayed correctly, like they are displayed if navigating the plugins from the listview.

The addon generates the playlist correctly in both cases: if I hold the OK button to show the current playlist it shows the elements correctly in both cases.

- It might be a "Skin Shortcut" related problem.
- The standard kodi skin does not display this difference.

The image attached show the difference:
![screenshot00002](https://user-images.githubusercontent.com/426049/147565068-de837d08-d287-49cd-ae5e-dad0585ffadc.jpg)

**Comment by Ch1llb0** [comment]
Thx for reporting this bug!

The issue should be fixed in our staging repo via this commit: https://github.com/osmc/skin.osmc/commit/0e1993a7c163c648d38be8bb372e2d30b051b765
It should now behave exactly like Estuary 👍🏻
