### ISSUE TITLE
Seekbar is not working

### ISSUE THREAD

**Issue by Desz5** [osmc/skin.osmc#438]
After i install Kodi and install the skin everything works, except when i play a file.
The video plays normally but the seekbar on the OSD isn't working at all.
I can click on the timeline but the cursor seekbar isn't moving.
When i switch to any other skin the seekbar works again.
Am i doing something wrong?
I'm using Kodi v19 and the latest Matrix release of the OSMC skin.
Thank you!

**Comment by Ch1llb0** [comment]
Are you navigating to the seekbar via remote/keyboard keys or using a mouse? Which platform are you on?

**Comment by Desz5** [comment]
I'm on Windows 10, and using a keyboard and mouse to navigate but the seekbar doesn't move.
All other OSD buttons work like normal.

**Comment by Ch1llb0** [comment]
I've tested this on my Win10 test setup, using the latest Matrix version of our OSMC Skin, but I can't see any issue here using the keyboard: When opening the OSD with all of the OSD buttons, I can navigate to the seek bar via the up button and consequently move the seek position with the arrow keys... Not sure what I might be doing differently, but I can't seem to be able to reproduce the issue you're seeing using a keyboard. 🤔

The OSMC Skin is not properly made for mouse control. I can see that clicking on the seek bar with the mouse button doesn't work as expected. I can see whether this is trivially fixable, but it's not a priority really - the Matrix skin is pretty much EOL now as I've branched off the Nexus skin already.

**Comment by Desz5** [comment]
Yes you're right!
Using the keyboard works, sorry only tried the mouse.
It would be great if maybe this is an easy fix to implement it in Matrix and Nexus:relaxed:

**Comment by Ch1llb0** [comment]
Thx for confirming! Will keep this on the list, but I'm pretty sure there was some reason I wasn't able to implement this properly for mouse control. Just not sure atm what the reason was...

**Comment by Ch1llb0** [comment]
Good news! I've been able to figure out what the issue was 👍🏻 Will push this to the Nexus branch, but not sure the Matrix skin will get any more updates...

**Comment by Desz5** [comment]
Great! Looking forward to the Nexus build! :+1:

**Comment by Ch1llb0** [comment]
You might be in luck... I'm currently backporting improvements already made to the Nexus branch for the Leia skin - the fix for this issue will be amongst them. Keep your eyes peeled! 😊
