### ISSUE TITLE
RecentlyPlayed Playlists doesn't work

### ISSUE THREAD

**Issue by neovenex** [osmc/skin.osmc#439]
The following Playlists doesn't work as expected:

/extras/playlists/episodes_recentlyplayed.xsp
/extras/playlists/movies_recentlyplayed.xsp
/extras/playlists/tvshows_recentlyplayed.xsp

The Problem seems to be this rule:

```
<rule field="playcount" operator="lessthan"> 
  <value>1</value> 
</rule>
```
I changed it to:

```
<rule field="playcount" operator="greaterthan"> 
  <value>0</value> 
</rule>
```

and all is fine.

Maybe the following rule make sense, to not catch the in progress movies, like in this example:

[Last_played_movies example](https://kodi.wiki/view/Smart_playlists/Examples#Last_played_movies_(history))
```
<rule field="inprogress" operator="false" />
```

**Comment by Ch1llb0** [comment]
I've checked this and I don't see what's wrong with the playlists. When you change the "playcount" rule to _greaterthan_ 0, it'll leave you with a playlist of watched movies - the play count doesn't represent movies that have been played for a short moment, but entirely. So, if the play count is e.g. 1, it means that the movie has been played 100% one time. That's not what this playlist is for. It should return movies that have been played shortly, that have been started, but that haven't been finished - it's somewhat similar to "in progress", but it also includes those movies that are not marked as "in progress" in the library, but also those that have just been played for a second or so. But it doesn't include those that would show up in the "watched" playlist.

**Comment by neovenex** [comment]
Ok, then I didn't understand the purpose of the playlists correctly. Sorry for that.
I'll just create my own playlist for my needs.
