### ISSUE TITLE
[FR] Add Play Buttons for Speed

### ISSUE THREAD

**Issue by Gunnar-GO** [osmc/skin.osmc#456]
at least since Kodi 17 you can speed up or slow down the playpack while playing. It would be nice to have the option as buttons in the skin. since it is optional most skins doesn't have this option.

see https://kodi.wiki/view/Keymap#Player_built-in.27s

 PlayerControl(command)
     --> TempoUp, TempoDown, Tempo(value)

**Comment by samnazarko** [comment]
Not possible with hardware accelerated decoding, so not an ideal goal for our platform.

**Comment by Gunnar-GO** [comment]
as far as i read it depends on sync with playbackrate, why should the hardware-decoding be bothered by this?

also the buttons could be made optional, so no harm?

**Comment by samnazarko** [comment]
There’s not much point in adding something that won’t work. What platform are you using the skin on?

**Comment by Gunnar-GO** [comment]
an Kodi 20.2 @ FireTV

since it can work, why not have an option?

**Comment by samnazarko** [comment]
The focus of the OSMC skin is for OSMC supported platforms.

**Comment by Gunnar-GO** [comment]
why you are so sure, that it isn't working? have you tried?

also i asked before: 

> as far as i read it depends on sync with playbackrate, why should the hardware-decoding be bothered by this?

**Comment by samnazarko** [comment]
Because we test our software and hardware..

**Comment by Ch1llb0** [comment]
AFAIK, our skin does support this functionality: The buttons left and right of play/pause do control skipping as well as ff or rw, if you move right or left on them again...

But as @samnazarko says, there's not much point in this functionality on platforms that won't properly support it. Our skin does have these buttons to be able to be used on any Kodi platform.

**Comment by samnazarko** [comment]
It’ll work for ffmpeg (software) decode and a limited number of HW decoders. I don’t believe any ARM platform is one of them.

**Comment by Ch1llb0** [comment]
Sorry for the confusion, but I didn't read the initial post properly yesterday... It's indeed true that speeding up and down video playback is not supported by our skin. Honestly, I wasn't really aware of the feature until now.

How does Estuary present these controls?
