### ISSUE TITLE
December version of OSMC Skin don't shows media files over uPnP

### ISSUE THREAD

**Issue by Petr-Mi** [osmc/skin.osmc#471]
Hi,
December version of OSMC Skin don't shows media files over uPnP. Older version from 2023.08.1 it shows.
Other skins shows movie files over uPnP.

**Comment by Petr-Mi** [comment]
I have this issue with Serviio. And I tested Mezzmo, Emby next. All servers has same issue.
But I installed Jellyfin for end and thats work fine.
All server in last versions.

**Comment by Ch1llb0** [comment]
Please see here: https://discourse.osmc.tv/t/no-more-upnp-client-after-december-vero-v-update/96397/42?u=chillbo

**Comment by samnazarko** [comment]
Closing as we will pick it up on the forums.
