### ISSUE TITLE
Skin is not loading on Shield with kodi v18 leia

### ISSUE THREAD

**Issue by paderico** [osmc/skin.osmc#61]
Hi,
tried to use osmc.skin on kodi v18 on shield/android. Used your skin on the same device before upgrade on v17.6 without any issues. 
I deleted the old skin and installed the new one for v18. Tried to load skin but it doesnt change and falls back to standard estuary skin.

I added a debuglog while trieing to load the skin and it errors on 
15:46:13.811 T:7500   ERROR: Window Translator: Can't find window gameviewmode

DebugLog
https://pastebin.com/9UwgK4GP

By the way, osmc skin is my favourite one. So thanks and keep up the good work. I hope you can fix the loading issues.
Cheers

**Comment by samnazarko** [comment]
Can you check you're on the latest version of the skin?

**Comment by paderico** [comment]
yes I am on master today

**Comment by jsahlen** [comment]
I'm having a similar issue (also on Kodi v18 on Shield): the skin does load, but there are lots of missing textures, and also fonts, so it's unusable. RC5.2 (f2f5fefd76dd433b623926557ce565d12e8c768b) works perfectly. Thanks for the best Kodi skins out there!

**Comment by Ch1llb0** [comment]
So, you're saying that it's not working anymore after that commit you linked?

**Comment by jsahlen** [comment]
Yes, or at least `master` isn't. I haven't tried any other commits inbetween, so I'm not sure exactly what introduced the problem. I could try it out tomorrow if it would be helpful (and also provide relevant log messages.)

**Comment by Ch1llb0** [comment]
That would be good. I don't have a Shield to test - and of course, our skin is mainly made for osmc platforms. But it's strange why it's not working properly on other platforms. Here it's working just fine on Windows 10 with the stable v18 release version of Kodi.

**Comment by jsahlen** [comment]
Thanks, I'll get back to you with better info. I understand completely that OSMC is you target platform, so hopefully this is just something minor that would be an easy fix :)

**Comment by Ch1llb0** [comment]
If I can fix this, I will try... Already nice to know that people like the skin and would like to use it, no matter which platform.

**Comment by Ch1llb0** [comment]
Just checked again... There must be a bug in the Android version Kodi v18. There is no gameviewmode window anymore (see here: https://forum.kodi.tv/showthread.php?tid=298565&pid=2785910#pid2785910). It used to exist until roughly October 2018 and also the latest version of Estuary and Estouchy don't have that window anymore.

This should probably be reported to the guys building the Android Kodi releases. They seem to somehow be using the skin engine dated back to around October 2018 for some (or no) reason.

Baseline: This is not an OSMC skin bug.

**Comment by paderico** [comment]
Thanks for investigating even if shield is obviously not your primary dev target.
I have to correct myself. The skin is loading but no text is loading so I couldnt see the dialog if I want to keep the skin... so it changed back automatically to estuary. Nevertheless the error in the log is gone, but i am afraid this wasnt the issue i was encountering

I uploaded a pic of what the screen looks like after loading the skin

![img_20190211_183128984](https://user-images.githubusercontent.com/34010800/52581976-60dc4d80-2e2c-11e9-8eac-772a06a95bcb.jpeg)

debuglog:
https://pastebin.com/2gLFnfCe

**Comment by paderico** [comment]
ok by going backwards 3times or so i landed on the homescreen with pretty much working skin. 
so it was the starting dialog for first time start which didnt work

**Comment by graham8** [comment]
I've been testing this on an Android tablet.  I don't get the OSMC background for most of the time it's waiting for that 'accept this skin' only for a second before it reverts to Estouchy.  Is that what you are seeing?

**Comment by Ch1llb0** [comment]
I've seen that bug before. Have you been using the v18 skin before on that particular device?

**Comment by paderico** [comment]
no problem i will test when merged

**Comment by Ch1llb0** [comment]
It's merged. Testing here showed that it should be working fine now.

**Comment by jsahlen** [comment]
Wow, that's amazing. I wasn't able to find the time yesterday to do any thorough testing, but I see a lot has happened here :) Looking forward to trying out the new version!

**Comment by paderico** [comment]
I will test tmr or Thursday since I am travelling atm

**Comment by jsahlen** [comment]
Works well for me!

**Comment by Ch1llb0** [comment]
So, no issues for you anymore, @jsahlen? If @paderico reports the same, we can close this issue.

**Comment by jsahlen** [comment]
No issues 👍 I copied my `v18alpha` settings, and they worked fine as well.

**Comment by paderico** [comment]
awesome everything is now working as expected and no more issues after a clean reinstallation!
Thank you very much for fixing the skin on the shield and your really quick adaption work! 👍

**Comment by Ch1llb0** [comment]
Glad to hear this. I'll close this issue now.

If there's anything else or if you have ideas for improvement, please do post them on our forum - they're always welcome.
