### ISSUE TITLE
Thumbnails not shown in "Large" mode since 17.9.3-46

### ISSUE THREAD

**Issue by louiz** [osmc/skin.osmc#69]
Reproduce like this : 
- Open a Serie or a Movie saga that has more than one season (or movie)
- When displaying the list of episodes in Large, no image appear. In every other mode (Wide low, Wall, etc) everything works just fine

This is broken up until 17.9.3-52, afaict. Downgrading with `apt install mediacenter-skin-osmc=17.9.3-45` fixes this regression.

**Comment by Ch1llb0** [comment]
Could you please upload a screenshot to shows us the issue (before/after)?

**Comment by louiz** [comment]
The menu path is : 
Main menu -> Series -> Dr House
Everywhere else, we see the images (in the list of series, in the list of movies etc) even if they are displayed in "Large" mode. Only the list of Seasons OR list of movies that are part of a Saga have this bug, and only in Large mode.

Here are the screenshots : 
https://pix.louiz.org/o/ZSulg.png is version 17.9.3-45
https://pix.louiz.org/o/tHHtS.png is version 17.9.3-46 up to 17.9.3-52

I couldn't fix it by clearing the Thumbnails, either (removing the userdata/Thumbnails and thumbailds.nb files). Only downgrading worked.

**Comment by Ch1llb0** [comment]
I'll check this here as well. Didn't notice any bug myself, but could've overlooked it. Thanks for the screenshots and the version numbers. 👍

**Comment by Ch1llb0** [comment]
Found the bug. This will be fixed in one of the next nightlies.

**Comment by louiz** [comment]
Awesome, thank you.
